
# Site settings
title: Artificial Intelligence for Stanford Pre-Collegiate Studies 
email: mahaugen@stanford.edu
description: ""
baseurl: "ai"
url: "http://matzhaugen.github.io/ai"

# Build settings
permalink: pretty
